sudo: false
language: perl

before_install:
  - export VIENNARNA_VERSION=2.2.8

install:
  - wget https://www.tbi.univie.ac.at/RNA/download/sourcecode/2_2_x/ViennaRNA-${VIENNARNA_VERSION}.tar.gz
  - tar -xzvf ViennaRNA-${VIENNARNA_VERSION}.tar.gz
  - cd ViennaRNA-${VIENNARNA_VERSION}/
  - ./configure --without-perl --without-python --without-python3
  - make
  - export PATH=$PATH:$PWD/src/bin
  - cpanm Bio::TreeIO
  - cpanm Statistics::Lite

script:
  - $TRAVIS_BUILD_DIR/run_tests.sh
